# This code sets the visual thmese for the Streamlit interface.
[theme]
primaryColor = "#003366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F0E1"
textColor = "#000000"
font = "sans serif"
