# This code specifies the email adress from where the mails will be sent, as the security settings.
smtp_server = "smtp.example.com"
smtp_port = 465
smtp_user = "700368nn@student.eur.nl"
smtp_password = "Password123"
sender_email = "700368nn@student.eur.nl"
